/**
 * MOCK DATA — used when the backend (localhost:8000) is unreachable.
 * Provides a fully functional offline demo experience.
 */
import type {
  Trip,
  DigitalTwinGraphData,
  RecoveryPlan,
  RecoveryHistoryEntry,
  ImpactAssessment,
} from './types';

// ── Trip ──────────────────────────────────────────────────────────────────
export const MOCK_TRIP: Trip = {
  id: 1,
  title: 'Mumbai to London Business Trip',
  version: 1,
  user_id: 1,
  created_at: '2026-09-07T00:00:00Z',
  items: [
    {
      id: 1, trip_id: 1, type: 'FLIGHT', provider: 'Air India',
      origin: 'Mumbai (BOM)', destination: 'Delhi (DEL)',
      start_time: '2026-09-07T08:30:00', end_time: '2026-09-07T10:30:00',
      cost: 8500, currency: 'INR', priority: 'HIGH', flexibility: 'FLEXIBLE',
      status: 'CONFIRMED', booking_id: 'AI-2091',
      refundable: true, refund_percentage: 80, cancellation_fee: 1700,
    },
    {
      id: 2, trip_id: 1, type: 'FLIGHT', provider: 'British Airways',
      origin: 'Delhi (DEL)', destination: 'London (LHR)',
      start_time: '2026-09-07T13:10:00', end_time: '2026-09-07T19:10:00',
      cost: 42000, currency: 'INR', priority: 'HIGH', flexibility: 'STRICT',
      status: 'CONFIRMED', booking_id: 'BA-5521',
      refundable: true, refund_percentage: 70, cancellation_fee: 12600,
    },
    {
      id: 3, trip_id: 1, type: 'TRANSFER', provider: 'Heathrow Express',
      origin: 'London (LHR)', destination: 'London City',
      start_time: '2026-09-07T21:55:00', end_time: '2026-09-07T22:40:00',
      cost: 2200, currency: 'INR', priority: 'MEDIUM', flexibility: 'VERY_FLEXIBLE',
      status: 'CONFIRMED', booking_id: 'HEX-007',
      refundable: true, refund_percentage: 100, cancellation_fee: 0,
    },
    {
      id: 4, trip_id: 1, type: 'HOTEL', provider: 'Marriott London',
      location: 'London',
      start_time: '2026-09-07T23:30:00', end_time: '2026-09-11T11:30:00',
      cost: 36000, currency: 'INR', priority: 'HIGH', flexibility: 'FLEXIBLE',
      status: 'CONFIRMED', booking_id: 'MAR-LON-8821',
      refundable: true, refund_percentage: 90, cancellation_fee: 3600,
    },
    {
      id: 5, trip_id: 1, type: 'EVENT', provider: 'Tech Conference 2026',
      location: 'ExCeL London',
      start_time: '2026-09-08T07:10:00', end_time: '2026-09-08T15:30:00',
      cost: 15000, currency: 'INR', priority: 'CRITICAL', flexibility: 'FIXED',
      status: 'CONFIRMED', booking_id: 'TC2026-KN',
      refundable: false, refund_percentage: 0, cancellation_fee: 15000,
    },
    {
      id: 6, trip_id: 1, type: 'FLIGHT', provider: 'Virgin Atlantic',
      origin: 'London (LHR)', destination: 'Mumbai (BOM)',
      start_time: '2026-09-11T01:30:00', end_time: '2026-09-11T15:00:00',
      cost: 38000, currency: 'INR', priority: 'MEDIUM', flexibility: 'FLEXIBLE',
      status: 'CONFIRMED', booking_id: 'VS-9901',
      refundable: true, refund_percentage: 75, cancellation_fee: 9500,
    },
  ],
};

// ── Graph ──────────────────────────────────────────────────────────────────
export const MOCK_GRAPH: DigitalTwinGraphData = {
  node_count: 6,
  edge_count: 5,
  nodes: [
    { id: '1', type: 'FLIGHT', provider: 'Air India', title: 'Mumbai \u2192 Delhi', route: 'BOM\u2192DEL', start_time: '2026-09-07T08:30:00', end_time: '2026-09-07T10:30:00', priority: 'HIGH', flexibility: 'FLEXIBLE', status: 'CONFIRMED' },
    { id: '2', type: 'FLIGHT', provider: 'British Airways', title: 'Delhi \u2192 London', route: 'DEL\u2192LHR', start_time: '2026-09-07T13:10:00', end_time: '2026-09-07T19:10:00', priority: 'HIGH', flexibility: 'STRICT', status: 'CONFIRMED' },
    { id: '3', type: 'TRANSFER', provider: 'Heathrow Express', title: 'LHR \u2192 London City', route: 'LHR\u2192CTY', start_time: '2026-09-07T21:55:00', end_time: '2026-09-07T22:40:00', priority: 'MEDIUM', flexibility: 'VERY_FLEXIBLE', status: 'CONFIRMED' },
    { id: '4', type: 'HOTEL', provider: 'Marriott London', title: 'Marriott London Check-in', route: 'London', start_time: '2026-09-07T23:30:00', end_time: '2026-09-11T11:30:00', priority: 'HIGH', flexibility: 'FLEXIBLE', status: 'CONFIRMED' },
    { id: '5', type: 'EVENT', provider: 'Tech Conference 2026', title: 'Tech Conference 2026 Keynote', route: 'ExC\u00e9L London', start_time: '2026-09-08T07:10:00', end_time: '2026-09-08T15:30:00', priority: 'CRITICAL', flexibility: 'FIXED', status: 'CONFIRMED' },
    { id: '6', type: 'FLIGHT', provider: 'Virgin Atlantic', title: 'London \u2192 Mumbai', route: 'LHR\u2192BOM', start_time: '2026-09-11T01:30:00', end_time: '2026-09-11T15:00:00', priority: 'MEDIUM', flexibility: 'FLEXIBLE', status: 'CONFIRMED' },
  ],
  edges: [
    { source: '1', target: '2', dependency_type: 'SEQUENTIAL', min_connection_minutes: 90, scheduled_buffer_minutes: 160 },
    { source: '2', target: '3', dependency_type: 'ARRIVAL_DEPENDENCY', min_connection_minutes: 45, scheduled_buffer_minutes: 165 },
    { source: '3', target: '4', dependency_type: 'SEQUENTIAL', min_connection_minutes: 30, scheduled_buffer_minutes: 50 },
    { source: '4', target: '5', dependency_type: 'CO_LOCATION', min_connection_minutes: 60, scheduled_buffer_minutes: 480 },
    { source: '4', target: '6', dependency_type: 'SEQUENTIAL', min_connection_minutes: 120, scheduled_buffer_minutes: 3600 },
  ],
};

// ── Recovery Plans ─────────────────────────────────────────────────────────
export const MOCK_RECOVERY_PLANS: RecoveryPlan[] = [
  {
    plan_id: 'mock-rec',
    strategy_type: 'REROUTE',
    title: 'Alternate Hub Reroute (via Doha)',
    description: 'Rebook via Qatar Airways through Doha. Arrives 3h before conference.',
    feasibility: true,
    infeasibility_reasons: [],
    preserves_critical_commitment: true,
    overall_score: 87.4,
    additional_delay_minutes: 95,
    additional_delay_str: '+1h 35m',
    new_booking_cost: 54000,
    additional_cost: 54000,
    change_fees: 0,
    cancellation_fees: 10200,
    net_cost: 43800,
    currency: 'INR',
    is_recommended: true,
    confidence: 'HIGH',
    explanation_summary: 'Qatar Airways QR-556 (BOM\u2192DOH) + QR-001 (DOH\u2192LHR). Arrives 3h before conference. Fully feasible.',
    traveler_summary: "Your rebooked route goes through Doha. You'll arrive in London 3 hours before your conference keynote — fully protected.",
    explanation_details: {},
    removed_items: [{ provider: 'Air India', origin: 'Mumbai (BOM)', destination: 'Delhi (DEL)' }, { provider: 'British Airways', origin: 'Delhi (DEL)', destination: 'London (LHR)' }],
    modified_items: [],
    added_items: [{ provider: 'Qatar Airways Leg 1', origin: 'Mumbai (BOM)', destination: 'Doha (DOH)' }, { provider: 'Qatar Airways Leg 2', origin: 'Doha (DOH)', destination: 'London (LHR)' }],
    trade_offs: { what_you_gain: 'Preserved: Marriott London, Tech Conference 2026, Virgin Atlantic', what_you_give_up: '95m transit delay; Cancellations: Air India, British Airways' },
    quality_metrics: { critical_preservation_score: 100, delay_score: 72, financial_score: 68, itinerary_preservation_score: 65, inconvenience_score: 60, preference_score: 80, overall_recovery_score: 87, components_preserved: 4, components_modified: 0, components_removed: 2, components_added: 2, affected_percentage: 83, critical_components_affected: 0 },
  },
  {
    plan_id: 'mock-cheap',
    strategy_type: 'NEXT_AVAILABLE',
    title: 'Next Direct Flight (IndiGo)',
    description: 'Next available direct London flight via IndiGo. Cheapest option.',
    feasibility: true,
    infeasibility_reasons: [],
    preserves_critical_commitment: true,
    overall_score: 79.1,
    additional_delay_minutes: 240,
    additional_delay_str: '+4h',
    new_booking_cost: 38000,
    additional_cost: 38000,
    change_fees: 3500,
    cancellation_fees: 10200,
    net_cost: 31300,
    currency: 'INR',
    is_recommended: false,
    confidence: 'MEDIUM',
    explanation_summary: 'IndiGo 6E-1441 departs Delhi 18:30, arrives LHR 23:15. Conference protected with 8h buffer.',
    traveler_summary: 'Next available via IndiGo — arrives well before conference. Cheapest option with a 4-hour delay.',
    explanation_details: {},
    removed_items: [{ provider: 'Air India', origin: 'Mumbai (BOM)', destination: 'Delhi (DEL)' }],
    modified_items: [{ provider: 'British Airways', type: 'Modified departure time' }],
    added_items: [{ provider: 'IndiGo', origin: 'Delhi (DEL)', destination: 'London (LHR)' }],
    trade_offs: { what_you_gain: 'Lowest cost; Conference fully preserved', what_you_give_up: '4h delay; Change fee on British Airways' },
    quality_metrics: { critical_preservation_score: 100, delay_score: 45, financial_score: 88, itinerary_preservation_score: 78, inconvenience_score: 70, preference_score: 65, overall_recovery_score: 79, components_preserved: 5, components_modified: 1, components_removed: 1, components_added: 1, affected_percentage: 50, critical_components_affected: 0 },
  },
  {
    plan_id: 'mock-fast',
    strategy_type: 'EXPRESS_TRANSFER',
    title: 'Station EV Shuttle Service',
    description: 'Priority EV shuttle directly to conference venue. Fastest, nearly free.',
    feasibility: true,
    infeasibility_reasons: [],
    preserves_critical_commitment: true,
    overall_score: 73.5,
    additional_delay_minutes: 15,
    additional_delay_str: '+15m',
    new_booking_cost: 300,
    additional_cost: 300,
    change_fees: 0,
    cancellation_fees: 2200,
    net_cost: -1900,
    currency: 'INR',
    is_recommended: false,
    confidence: 'HIGH',
    explanation_summary: 'EV Shuttle direct to ExC\u00e9L London in 35 min. Faster and cheaper than Heathrow Express.',
    traveler_summary: 'A priority EV shuttle takes you straight to ExC\u00e9L London in 35 minutes — faster and cheaper than the train.',
    explanation_details: {},
    removed_items: [{ provider: 'Heathrow Express', origin: 'London (LHR)', destination: 'London City' }],
    modified_items: [],
    added_items: [{ provider: 'Station EV Shuttle', origin: 'London (LHR)', destination: 'London City' }],
    trade_offs: { what_you_gain: 'Preserved: Air India, British Airways, Marriott London, Tech Conference 2026, Virgin Atlantic', what_you_give_up: '15m transit delay; Cancellation: Heathrow Express' },
    quality_metrics: { critical_preservation_score: 100, delay_score: 95, financial_score: 95, itinerary_preservation_score: 95, inconvenience_score: 90, preference_score: 80, overall_recovery_score: 73, components_preserved: 5, components_modified: 0, components_removed: 1, components_added: 1, affected_percentage: 17, critical_components_affected: 0 },
  },
];

// ── Impact Assessment (Flight Delay) ──────────────────────────────────────
export const MOCK_IMPACT_FLIGHT_DELAY: ImpactAssessment = {
  trip_id: 1,
  event_type: 'FLIGHT_DELAY_4H',
  entity_id: 1,
  total_components: 6,
  components_affected: 4,
  affected_percentage: 67,
  critical_components: 1,
  critical_components_affected: 1,
  impact_score: 85,
  node_impacts: {
    '1': { id: '1', type: 'FLIGHT', title: 'Air India Mumbai\u2192Delhi', priority: 'HIGH', impact_status: 'AFFECTED', reason: 'Delayed 240 minutes \u2014 departure pushed to 12:30', original_start: '2026-09-07T08:30:00', simulated_start: '2026-09-07T12:30:00', details: { delay_minutes: 240 } },
    '2': { id: '2', type: 'FLIGHT', title: 'British Airways Delhi\u2192London', priority: 'HIGH', impact_status: 'MISSED', reason: 'Missed connection \u2014 arrives after BA-5521 departure', original_start: '2026-09-07T13:10:00', simulated_start: '2026-09-07T13:10:00', details: {} },
    '5': { id: '5', type: 'EVENT', title: 'Tech Conference 2026 Keynote', priority: 'CRITICAL', impact_status: 'AT_RISK', reason: 'Conference attendance at risk if no alternative found', original_start: '2026-09-08T07:10:00', simulated_start: '2026-09-08T07:10:00', details: {} },
  },
  cascade_paths: [['1', '2', '5']],
  summary: 'Air India flight delayed 4 hours. This causes a missed connection in Delhi, putting the Tech Conference 2026 keynote at serious risk. Immediate rebooking required.',
};

// ── History ────────────────────────────────────────────────────────────────
export const MOCK_HISTORY: RecoveryHistoryEntry[] = [
  {
    id: 1,
    recovery_id: 'rec-001',
    previous_version: 1,
    new_version: 2,
    event_type: 'FLIGHT_DELAY_4H',
    selected_plan_id: 'mock-rec',
    plan_title: 'Alternate Hub Reroute (via Doha)',
    net_cost: 43800,
    additional_delay_minutes: 95,
    changes: {},
    status: 'EXECUTED',
    timestamp: '2026-09-05T14:32:00Z',
  },
];
