from enum import Enum

class EventType(str, Enum):
    DELAY = "DELAY"
    CANCELLATION = "CANCELLATION"
    AIRPORT_CLOSURE = "AIRPORT_CLOSURE"
    WEATHER = "WEATHER"
    FLIGHT_CHANGE = "FLIGHT_CHANGE"
    TRAIN_DELAY = "TRAIN_DELAY"
    TRAIN_CANCEL = "TRAIN_CANCEL"
    MISSED_TRAIN = "MISSED_TRAIN"
    HOTEL_UNAVAILABLE = "HOTEL_UNAVAILABLE"
    CHECKIN_MISSED = "CHECKIN_MISSED"
    TRANSFER_FAILURE = "TRANSFER_FAILURE"
    TRANSFER_DELAY = "TRANSFER_DELAY"
    ACTIVITY_CANCELLED = "ACTIVITY_CANCELLED"
    ACTIVITY_MISSED = "ACTIVITY_MISSED"
    USER_REQUESTED_CHANGE = "USER_REQUESTED_CHANGE"
    USER_REQUESTED_CANCELLATION = "USER_REQUESTED_CANCELLATION"

class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
